pass Handler's event loop to asyncio.Lock()
my use case of aiologger is one where I'm using several class instances, each endowed with their own Logger.  Every class instance also has its own event loop, which I pass to the Logger and AsyncStreamHandler on init.  

With this design I am currently encountering RuntimeErrors with the following traceback:

```
RuntimeError: Task <Task pending coro=<Logger._log() running at usr/lib/python3.6/site-packages/aiologger/logger.py:225>> got Future <Future pending> attached to a different loop
Task exception was never retrieved
future: <Task finished coro=<Logger._log() done, defined at usr/lib/python3.6/site-packages/aiologger/logger.py:186> exception=RuntimeError('Task <Task pending coro=<Logger._log() running at usr/lib/python3.6/site-packages/aiologger/logger.py:225>> got Future <Future pending> attached to a different loop',)>
Traceback (most recent call last):
  File "usr/lib/python3.6/site-packages/aiologger/logger.py", line 225, in _log
    await self.handle(record)
  File "usr/lib/python3.6/site-packages/aiologger/logger.py", line 184, in handle
    await self.call_handlers(record)
  File "usr/lib/python3.6/site-packages/aiologger/logger.py", line 154, in call_handlers
    await handler.handle(record)
  File "usr/lib/python3.6/site-packages/aiologger/handlers/streams.py", line 68, in handle
    await self.emit(record)
  File "usr/lib/python3.6/site-packages/aiologger/handlers/streams.py", line 79, in emit
    self.writer = await self._init_writer()
  File "usr/lib/python3.6/site-packages/aiologger/handlers/streams.py", line 45, in _init_writer
    async with self._initialization_lock:
  File "/usr/lib/python3.6/asyncio/locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "/usr/lib/python3.6/asyncio/locks.py", line 181, in acquire
    yield from fut
```

Is it sensible that `_initialization_lock` would be forced to use the handler's own event loop? After making this change in the source code the RuntimeErrors have stopped.